/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.usjt.firebook.firebook;

import javax.swing.JOptionPane;

/**
 *
 * @author 823218506
 */
public class CadastroLivroTela extends javax.swing.JFrame {
    
    Usuario logado;

    /**
     * Creates new form CadastroLivroTela
     */
    public CadastroLivroTela() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public CadastroLivroTela(Usuario logado) {
        this();
        this.logado = logado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generoGroup = new javax.swing.ButtonGroup();
        notaTextField = new javax.swing.JTextField();
        tituloTextField = new javax.swing.JTextField();
        voltarButton = new javax.swing.JButton();
        cadastrarButton = new javax.swing.JButton();
        romanceRadioButton = new javax.swing.JRadioButton();
        ficcaoRadioButton = new javax.swing.JRadioButton();
        tecnicoRadioButton = new javax.swing.JRadioButton();
        generoLabel = new javax.swing.JLabel();
        cadastrarNovoLivroLabel = new javax.swing.JLabel();
        autorTextField = new javax.swing.JTextField();
        loginTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(385, 405));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota"));
        getContentPane().add(notaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 310, 41));

        tituloTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulo"));
        getContentPane().add(tituloTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 310, 41));

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 150, 40));

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 150, 40));

        generoGroup.add(romanceRadioButton);
        romanceRadioButton.setText("Romance");
        romanceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                romanceRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(romanceRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        generoGroup.add(ficcaoRadioButton);
        ficcaoRadioButton.setText("Ficção");
        getContentPane().add(ficcaoRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        generoGroup.add(tecnicoRadioButton);
        tecnicoRadioButton.setText("Técnico");
        getContentPane().add(tecnicoRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        generoLabel.setText("Genero:");
        getContentPane().add(generoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 230, -1));

        cadastrarNovoLivroLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        cadastrarNovoLivroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrarNovoLivroLabel.setText("Cadastrar Novo Livro");
        getContentPane().add(cadastrarNovoLivroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 310, 50));

        autorTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Autor"));
        getContentPane().add(autorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 310, 41));

        loginTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Autor"));
        getContentPane().add(loginTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 310, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        var dut = new DashboardUsuarioTela(logado);
        dut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        
        //atribui ao livro dados simples do livro recebidos do formulario
        Livro livro = new Livro();
        livro.setTitulo(tituloTextField.getText());
        livro.setAutor(autorTextField.getText());
        
        //atribui ao livro o codigo do genero selecionado
        if (romanceRadioButton.isSelected()){
            livro.setIdGenero(1);
        }
        if (ficcaoRadioButton.isSelected()){
            livro.setIdGenero(2);
        }
        if (tecnicoRadioButton.isSelected()){
            livro.setIdGenero(3);
        }
        
        //atribui ao livro o ID do usuario que o cadastrou
        livro.setIdUsuario(logado.getIdUsuario());
        
        try {
            LivroDAO.cadastrar(livro);
            LivroDAO.receberDados(livro);
            
            Avaliacao avaliacao = new Avaliacao();
            avaliacao.setNota(Double.parseDouble(notaTextField.getText()));
            avaliacao.setIdLivro(livro.getIdLivro());
            avaliacao.setIdUsuario(logado.getIdUsuario());
            AvaliacaoDAO.cadastrar(avaliacao);
            
            System.out.println("Livro cadastrado com sucesso!");

            JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso!");
            
            var dut = new DashboardUsuarioTela(logado);
            dut.setVisible(true);
            this.dispose();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog (null, "Erro ao cadastrar o livro/avaliacao");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void romanceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_romanceRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_romanceRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autorTextField;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JLabel cadastrarNovoLivroLabel;
    private javax.swing.JRadioButton ficcaoRadioButton;
    private javax.swing.ButtonGroup generoGroup;
    private javax.swing.JLabel generoLabel;
    private javax.swing.JTextField loginTextField2;
    private javax.swing.JTextField notaTextField;
    private javax.swing.JRadioButton romanceRadioButton;
    private javax.swing.JRadioButton tecnicoRadioButton;
    private javax.swing.JTextField tituloTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
