/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.bello_academico.entrega01;

import javax.swing.JOptionPane;

/**
 *
 * @author 819226747
 */
public class LoginTela extends javax.swing.JFrame {

    /**
     * Creates new form LoginTela
     */
    public LoginTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        LoginTextField = new javax.swing.JTextField();
        SenhaPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        FazerLoginButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CancelarLoginButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite seu usuário"));
        LoginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(LoginTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 120, 38));

        SenhaPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite sua senha"));
        SenhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(SenhaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 120, -1));

        jLabel1.setText("      FireBook");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 74, 35));

        FazerLoginButton.setText("Login");
        FazerLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FazerLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FazerLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jButton1.setText("Esqueceu a senha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        CancelarLoginButton.setText("cancelar");
        CancelarLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelarLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginTextFieldActionPerformed

    private void SenhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaPasswordFieldActionPerformed

    private void FazerLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FazerLoginButtonActionPerformed
        // TODO add your handling code here:
        //passo 1: login
          String login = LoginTextField.getText();
        //passo 2: senha
          String senha = new String(SenhaPasswordField.getPassword()); 
        //passo 3: verificar
        if (login.equals("admin") && senha.equals("admin")){
        //passo 4: entrou
         JOptionPane.showMessageDialog(null, "bem vindo!");
                }
        else{
        //passo 5: errou
                JOptionPane.showMessageDialog(null, "senha e/ou login errados");
        }
        
    }//GEN-LAST:event_FazerLoginButtonActionPerformed

    private void CancelarLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarLoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarLoginButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarLoginButton;
    private javax.swing.JButton FazerLoginButton;
    private javax.swing.JTextField LoginTextField;
    private javax.swing.JPasswordField SenhaPasswordField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
